### ISSUE TITLE
Removed backtick causes compiler to fail

### ISSUE THREAD

**Issue by 3lvis** [nicklockwood/SwiftFormat#114]
## Installed version (brew): swiftformat, version 0.26.2

Before I had:

```swift
static var type: Build.`Type` {
```

Now I have:

```swift
static var type: Build.Type {
```

Swift is not smart enough to figure it out without the backtick.

Full class:

```swift
import Foundation

struct Build {
    enum `Type`: String {
        case alpha
        case beta
        case production
    }

    static var type: Build.`Type` {
        let bundleIdentifier = Bundle.main.bundleIdentifier
        let components = bundleIdentifier!.components(separatedBy: ".")
        let lastComponent = components.last!

        if let type = self.Type(rawValue: lastComponent) {
            return type
        } else {
            return .production
        }
    }
}
```

**Comment by nicklockwood** [comment]
Thanks, I'll look into it.

**Comment by nicklockwood** [comment]
Fixed in 0.27.0

**Comment by 3lvis** [comment]
Fantastic, thanks!

**Comment by 3lvis** [comment]
Still happening in version 0.28.1

<img width="528" alt="screen shot 2017-03-30 at 15 35 34" src="https://cloud.githubusercontent.com/assets/1088217/24506721/af844be2-155e-11e7-8292-712bb359f7a5.png">

**Comment by 3lvis** [comment]
Doesn't seem like I can reopen this issue, could you do it for me>?

**Comment by nicklockwood** [comment]
Sorry about that, I thought it was fixed, but it seems not. I'll take another look.

**Comment by nicklockwood** [comment]
Fixed in 0.28.2
