### ISSUE TITLE
Console errors after update to 0.49.10

### ISSUE THREAD

**Issue by katovBash** [nicklockwood/SwiftFormat#1201]
**After release 0.49.10 there was appeared error: make: *** [format] Error 70.** 

In console we can find: 
error: Unexpected end of file at 24:77 
error: Unexpected end of file at 20:30
error: Expected end of scope on line 218
and etc. in different files. 

In xCode all is fine. **Its build and all brackets are in current place :)**

**Comment by nicklockwood** [comment]
Hi, can you provide the file that produces this error? You can send it privately to support @ charcoaldesign.co.uk if you'd prefer not to make it public.

**Comment by nicklockwood** [comment]
Ah OK, so this is using the CasePaths library, right? I suspect it's related to https://github.com/nicklockwood/SwiftFormat/issues/1199

**Comment by katovBash** [comment]
All right. Ok, thanks)

**Comment by nicklockwood** [comment]
@katovBash fixed in 0.49.11

**Comment by katovBash** [comment]
@nicklockwood 
ver. 0.49.11
hmm... errors become lesser, but it still appeared
Still error in file, that was clipped. 
Error: "error: Unexpected end of file at 20:30"
