### ISSUE TITLE
with --self insert: decomposing associated value with same name as member var causes confusion

### ISSUE THREAD

**Issue by aliak00** [nicklockwood/SwiftFormat#129]
```
enum Test<T> {
    case a(T)
    case b
    var value: T? {
        if case let .a(value) = self { // self inserted here after running swift format
            return value
        }
        return nil
    }
}
```

**Comment by aliak00** [comment]
Just realized I'm on 28.1. Maybe it's fixed in an update. Will check and report if you don't get to seeing this first.

**Comment by nicklockwood** [comment]
@aliak00 looks like it's still reproducible on 28.3. I'll take a look.

**Comment by nicklockwood** [comment]
@aliak00 fixed in 0.28.4
