### ISSUE TITLE
Reformatting `try` out of XCTAssertEqual call breaks the source

### ISSUE THREAD

**Issue by guillaumealgis** [nicklockwood/SwiftFormat#1372]
Since upgrading to 0.51.0, SwiftFormat tries (pun unintended) to reformat the following code by moving the `try`s out of the function call, but fails and makes the code invalid:  

Before:

```swift
import UIKit

func XCTAssertEqual(_ a: NSDictionary, _ b: NSDictionary) {
    print(a, b)
}

let firstData = Data("{}".utf8)
let secondData = Data("{}".utf8)

// ------------------

XCTAssertEqual(
    try JSONSerialization.jsonObject(with: firstData) as! NSDictionary,
    try JSONSerialization.jsonObject(with: secondData) as! NSDictionary
)
```

```sh
$ swiftformat --version
0.51.0
$ swiftformat --swiftversion 5.7 Contents.swift 
```

After:

```swift
import UIKit

func XCTAssertEqual(_ a: NSDictionary, _ b: NSDictionary) {
    print(a, b)
}

let firstData = Data("{}".utf8)
let secondData = Data("{}".utf8)

// ------------------

XCTAssertEqual(try
    JSONSerialization.jsonObject(with: firstData) as! NSDictionary,
    JSONSerialization.jsonObject(with: secondData) as! NSDictionary)
```

This seems related to the `XCTAssert` part of the function name, I could not reproduce when the function is named something else.

---------------

**Workaround**: The code can be fixed manually (by moving the `try` in front of `XCTAssertEqual`) and SwiftFormat will not mess with it anymore.

**Comment by nicklockwood** [comment]
@guillaumealgis fixed in 0.51.1

**Comment by guillaumealgis** [comment]
Great! Thanks @nicklockwood !

![172g5x-2](https://user-images.githubusercontent.com/1041337/222413320-db6d5259-f005-4fdd-8842-0aba2de9f3b7.jpg)

**Comment by alanf** [comment]
We still have this issue in the latest version:

```
 return KingfisherManager.shared.rx
            .retrieveImage(
                with: try components.url ?? error()
            )
            .map { image -> UIImage in
                guard let cgImage = image.cgImage else {
                    return image
                }
                return UIImage(cgImage: cgImage, scale: UIScreen.main.scale, orientation: image.imageOrientation)
            }
```
becomes erroneous with:

```
return KingfisherManager.shared.rx
            try .retrieveImage(
                with: components.url ?? error()
            )
            .map { image -> UIImage in
                guard let cgImage = image.cgImage else {
                    return image
                }
                return UIImage(cgImage: cgImage, scale: UIScreen.main.scale, orientation: image.imageOrientation)
            }
```

becomes:


And:
```
  let endpoint = Endpoint<DatadogAPIClient, String>
        .init(
            method: .get,
            path: (try components.path.nonEmpty ?? error()),
            query: .queryItems([
                URLQueryItem(name: "mobileembedview", value: "true"),
            ] + (components.queryItems ?? [])),
            headers: .mapClientDefault { $0.removingHeaders(for: .authorization) },
            output: .text
        )
        
```


Is getting transformed to:

```
try .init(
            method: .get,
            path: components.path.nonEmpty ?? error(),
            query: .queryItems([
                URLQueryItem(name: "mobileembedview", value: "true"),
            ] + (components.queryItems ?? [])),
            headers: .mapClientDefault { $0.removingHeaders(for: .authorization) },
            output: .text
        )
```
