### ISSUE TITLE
pre-commit hook example does not work for paths with spaces

### ISSUE THREAD

**Issue by timothy-volvo** [nicklockwood/SwiftFormat#144]
If the swift file resides in a folder with a space, the pre-commit example grep call doesn't match as there is a " at the end of the line. Here is a version that worked for me:

#!/bin/bash
 git status --porcelain | sed 's/"//g' | grep -e '^[AM]\(.*\).swift$' | cut -c 3- | while read line; do
   swiftformat "${line}";
   git add $line;
 done

**Comment by nicklockwood** [comment]
I've updated the README in version 0.29.0

**Comment by 1oo7** [comment]
Note: still have this issue on the latest SwiftFormat. 

```
git status --porcelain | sed 's/"//g' | grep -e '^[AM](.*).swift$' | cut -c 3- | while read line; do
swiftformat "${line}";
git add $line;
```

... did not work for some reason on macOS Mojave. I removed the anchor characters `^` and `$` from the grep regex, then it started working. Not sure why, but maybe this will help someone.
