### ISSUE TITLE
Swift Package Manager Xcode Command Plugin does not works on 0.52.9 and later

### ISSUE THREAD

**Issue by fthdgn** [nicklockwood/SwiftFormat#1594]
Xcode Version: 15.0.1 (15A507)
MacOS Version: Ventura 13.6.2

# Steps
* On project settings > Package Dependencies, clicked + and added "https://github.com/nicklockwood/SwiftFormat.git" with exact version 0.52.11. Selected "None" as target for all package products. (These products meant to be used by plugin, not my app target)
* Project successfully fetched and "SwiftFormatPlugin" is appeared on context menu of project item on navigation
* Clicked the context menu item, and selected the top level project and clicked run button.
* None of the files formatted and this log is printed on the report navigator. This is the "Plug-in" report:
```
Plugin is declared with the `command` capability, but doesn't conform to the `XcodeCommandPlugin` protocol
```
* On project settings > Package Dependencies, changed version to `0.52.10` and `0.52.9`, same error occured.
* Changed version to `0.52.8` and the plugin run successfully. This is the "Plug-in" report:
```
Running SwiftFormat...
Reading config file at /Users/***/Projects/my_project/.swiftformat
Reading swift-version file at /Users/**/Projects/my_project/.swift-version (version 5.9)
warning: Failed to create cache directory at /Users/**/Library/Caches/com.charcoaldesign.swiftformat.
SwiftFormat completed in 3.69s.
174/178 files formatted.
Formatted the source code in /Users/**/Projects/my_project.
```

**Comment by nicklockwood** [comment]
@fthdgn thanks for reporting this - could you perhaps open a pull request to fix it?

**Comment by fthdgn** [comment]
https://github.com/nicklockwood/SwiftFormat/compare/0.52.8...0.52.9

I checked this diff but cannot see any change may cause this problem.
I am planning to run each commit to pinpoint the commit which introduced the issue.

**Comment by fthdgn** [comment]
I found the problem. In a commit `Plugins/SwiftFormatPlugin/SwiftFormatPluginXcode.swift` is deleted. The protocol extension inside of this file is necessary to run by Xcode.

https://github.com/nicklockwood/SwiftFormat/commit/496a7cc0943874fcec0f35b9b73ff2fba4e15837#diff-96f7aaf9e74e9bc9781e14791fa1c79e671057a51920b7e597205ca29b1f7f4a

**Comment by fthdgn** [comment]
When I restore the file, plugin starts to work. But I am not sure why the code is deleted. If it is related to the other changes made in the commit, I don't fully understand them. Thus I am not opening a pull request yet.

@MahdiBM It seems like you authored the commit. Can you clarify the reason why you deleted the file?

**Comment by MahdiBM** [comment]
@fthdgn It was incompatible with figuring out the local dependencies of a target.
I highly doubt this is causing any issues. We have the same code in https://github.com/apple/swift-openapi-generator and i'm not aware of any problems caused by it there.

Let me check more.

**Comment by MahdiBM** [comment]
@fthdgn I can reproduce this ... now let me see what's the best solution.
We can just put back the file, i think that would be pretty fine although it wouldn't work as good as it should on Xcode, because it won't be able to figure out the local dependencies of a target (or maybe I'm mistaken and Xcode passes those to the plugin too)

**Comment by MahdiBM** [comment]
@fthdgn Looking more, i think you can just re-add the whole file that was removed, and it should be fine. 
Though i haven't tested this, so give it a try too so we know that it works.
I can make the PR myself too if you want.

**Comment by fthdgn** [comment]
I've opened a PR.

It works in my use case. I didn't test the local dependencies case.

What was the purpose of your commit? Does it enable code formatting on the directories added as local swift package?

**Comment by MahdiBM** [comment]
@fthdgn Pardon me if i mention some obvious stuff that you already know, but i want to be clear:

In a SwiftPM project, we can have multiple targets that do different things. For example we can have a "Core" target, then a "MyApp" and a "MyCLI" target, and the "MayApp" and "MyCLI" targets can depend on the "Core" target that provides the shared-core logic.

When openning a SwiftPM project in Xcode (NOT as an Xcode / iOS / macOS project that IIRC has a `.xcproject` file), when you want to run the command plugin, it would show a popup to you and ask you to choose any targets from a list of targets to run the plugin for. Those targets that it shows are always only the "product"s, the "executable" targets, or the "test" targets. This means that it might show "MyCLI" as a target to choose, but it won't show "Core" (assuming we don't export "Core" as a product).
This is a problem, because long-story short, we cannot have a way to ask the plugin to be run on _all_ our local dependencies. It will only be run on products, executables, or test targets of a package. But with the changes i made, it will run on all local dependencies of those targets as well (so "Core" included).

That's the reason for that PR.

**Comment by nicklockwood** [comment]
@fthdgn fix landed in 0.53.0

**Comment by vsanthanam** [comment]
I still see this issue in 100% of my package plugin uses on version 0.61.1, and have basically for the last 12 months regardless of what version I use. Deleting the cache file changes the error message slightly ("failed to create file " vs "failed to write cache"), but the effect is still that the plugin is unusable for me unless I use it in combination with `--cache ignore`, which makes it considerably slower than just running from my local install from homebrew
