### ISSUE TITLE
`enumNamespaces` applies even to types with macros attached

### ISSUE THREAD

**Issue by jshier** [nicklockwood/SwiftFormat#1635]
Lately, `enumNamespaces` has started treating simple `struct` declarations which have parts of their body synthesized by a macro as if they're namespaces. For example, this small, typical example from the Composable Architecture:

```swift
@Reducer
struct SummaryScreen {
    @ObservableState
    struct State: Equatable {
        let output: NewExpenseFlowOutput
        var isSubmittingExpense: Bool
    }
    enum Action: Equatable {
        case submitExpense
    }
    // Parent handles action.
}
```

This currently gets replaced by an `enum`. I'm not sure how, exactly, the heuristic can be updated to fix this. Perhaps just have the rule ignore types with macros or other attributes attached?

**Comment by nicklockwood** [comment]
@jshier fixed in 0.53.3

**Comment by jshier** [comment]
This doesn't appear fixed in 0.53.3. Perhaps the fact my type is more nested is the issue?

```swift
@Reducer
struct NewExpenseFeature: Reducer {
    @Reducer(state: .equatable, action: .equatable)
    enum Path {
        // Cases in presentation order.
        case expenseType(InputScreen)
        case reimbursementSource(InputScreen)
        case coinCraftType(InputScreen)
        case approver(InputScreen)
        case preferredBusiness(InputScreen)
        case details(DetailsScreen)
        case description(NextScreen)
        case receipt(InputScreen)
        case summary(SummaryScreen)

        @Reducer
        struct SummaryScreen {
            @ObservableState
            struct State: Equatable {
                let output: NewExpenseFlowOutput
                var isSubmittingExpense: Bool
            }

            enum Action: Equatable {
                case submitExpense
            }

            // Parent handles action.
        }
    }
}
```

In that example `SummaryScreen` still gets converted to an enum.

**Comment by nicklockwood** [comment]
@jshier it turns out I just messed up and only tested the new logic with classes, not structs 🤦‍♂️

**Comment by nicklockwood** [comment]
@jshier fixed in 0.53.4

**Comment by weakfl** [comment]
@nicklockwood I'm still experiencing this issue using version `0.53.7` with macros with a generic argument clause, eg:

```swift
@FooMacro<Int>
struct Bar {}
```

This still gets converted to:

```swift
@FooMacro<Int>
enum Bar {}
```

**Comment by nicklockwood** [comment]
> @nicklockwood I'm still experiencing this issue using version `0.53.7` with macros with a generic argument clause, eg:

I didn't actually realize macros could have generic arguments 😅 I'll get this fixed - thanks

**Comment by nicklockwood** [comment]
@weakfl fixed in 0.53.8

**Comment by weakfl** [comment]
Thanks @nicklockwood, works as expected
