### ISSUE TITLE
`sortDeclarations` silent failure

### ISSUE THREAD

**Issue by domkm** [nicklockwood/SwiftFormat#1708]
`sortDeclaration` silently fails to organize some types. Running with `--verbose` does not show any warnings or errors either.

Here is an example of a type that is not being sorted:

```swift
// swiftformat:sort
struct BookReaderView {
  @Namespace private var animation
  @State private var animationContent: Bool = false
  @State private var offsetY: CGFloat = 0
  @Bindable var model: Book
  @Query(
    filter: #Predicate<Alignment> { $0.progress_ < 1 },
    sort: \.updatedAt_,
    order: .reverse
  ) private var incompleteAlignments: [Alignment]
  @Query(
    filter: #Predicate<AudioContent> { $0.progress_ < 1 },
    sort: \.updatedAt_,
    order: .reverse
  ) private var incompleteAudioContents: [AudioContent]
  @Query(
    filter: #Predicate<TextContent> { $0.progress_ < 1 },
    sort: \.updatedAt_,
    order: .reverse
  ) private var incompleteTextContents: [TextContent]
}
```

My `.swiftformat`:
```
--disable headerFileName
--disable redundantSelf
--enable blankLineAfterImports
--enable blankLinesBetweenChainedFunctions
--enable blankLinesBetweenImports
--enable blockComments
--enable fileHeader
--enable isEmpty
--enable organizeDeclarations
--enable sortDeclarations
--enable sortSwitchCases
--enable sortTypealiases
--enable wrapEnumCases
--enable wrapSwitchCases

--allman false
--extensionacl on-declarations
--header strip
--indent 2
--markcategories false
--organizetypes class,actor,struct,enum,extension,protocol
```

**Comment by nicklockwood** [comment]
@domkm the problem appears to be caused by enabling `organizeDeclarations`, thought I'm not yet sure why.

@calda any idea what might be going on here?

**Comment by nicklockwood** [comment]
@calda OK I'm stumped. The sorting logic within organizeDeclarations ought to be doing the right thing here AFAICT, but it just... doesn't. I've no idea what's going on.

**Comment by nicklockwood** [comment]
@calda OK, I figured it out (finally). It's because of this:

```swift
// The compiler will synthesize a memberwise init for `struct`
// declarations that don't have an `init` declaration.
// We have to take care to not reorder any properties (but reordering functions etc is ok!)
if typeDeclaration.kind == "struct",
   !typeDeclaration.body.contains(where: { $0.keyword == "init" })
{
```

@domkm tl;dr; we can't re-order the properties here because it would break the synthesized initializer for the struct. If you were to declare an explicit initializer it would work.

@calda it seems inconsistent that the `sortDeclarations` rule on its own is happy to make this breaking change, but that the `organizeDeclarations` rule won't do it. Maybe if the user has explicitly requested sorting via the comment directive then we can just go ahead and apply the sorting anyway?

Also the lack of indication in the output for why it didn't apply the sorting seems not ideal. I wonder if it should print a warning or something to the console?

**Comment by calda** [comment]
Ahhhhh nice find!

I think we can disable that functionality when the sort annotation is applied explicitly.

**Comment by nicklockwood** [comment]
@calda just adding the check for explicit sort to that if statement seems to fix it. I'll let you know if I find any other issues 👍

**Comment by nicklockwood** [comment]
@domkm fixed in 0.54.0

**Comment by domkm** [comment]
I'm still experiencing this (or something very similar) using `0.54.1`. Here is an example and my config: https://gist.github.com/domkm/f52e4eba8ef78820e13ae6135b7af627

**Comment by calda** [comment]
@domkm, since you have `organizeDeclarations` enabled, the `swiftformat:sort` directive causes the alphabetical sorting to be applied in each subcategory, rather than in the file as a whole. This prevents `organizeDeclarations` and `sortDeclarations` from conflicting with each other.

In your sample code, all of the declarations in each individual subcategories are sorted alphabetically. 

I could imagine wanting `swiftformat:sort` to override `organizeDeclarations`, but that is not currently implemented as an option.

**Comment by domkm** [comment]
@calda Thanks for the explanation!

I find the organization very confusing. Why is sorting still being done by ACL when `organizationmode` is `type`? Why are `@ViewBuilder` vars separated from other vars? Why are computed properties organized with vars instead of functions? It would be awesome if this stuff was configurable (and if `sortDeclarations` could be enabled globally instead of by comment, like the other rules). What I actually want is just 2 sections where the first is stored properties (AKA state) and the second is everything else, each sorted alphabetically.

**Comment by calda** [comment]
The `type` mode organizes declarations first by type and then by ACL level. This was added by @oiuhr in https://github.com/nicklockwood/SwiftFormat/pull/1678.

https://github.com/nicklockwood/SwiftFormat/pull/1736 adds the ability to customize the sort ordering of these rules, and would let you change the ordering of things you mentioned like `@ViewBuilder`s, computed properties, functions, etc.

PRs are always welcome to add more configuration options! If you have specific suggestions or requests, I'd suggest opening a separate issue.
