### ISSUE TITLE
Incorrect error about missing bracket in `for await case let` loop

### ISSUE THREAD

**Issue by bbrk24** [nicklockwood/SwiftFormat#1974]
I got an error about a missing `{` on line 59 of a file. The relevant excerpt is

```swift
/*56*/       var responses: [Int: CalculatedResult] = [:]
/*57*/       for await case let (index, result)? in group {
/*58*/           responses[index] = result
/*59*/       }
/*60*/       return responses
```

I was initially baffled by the error, but then I figured that maybe it's confused by the `for await case let`. And indeed, rewriting it to not have that keyword string fixes it -- the following code gives no errors:

```swift
            var responses: [Int: CalculatedResult] = [:]
            for await thing in group {
                if let (index, result) = thing {
                    responses[index] = result
                }
            }
            return responses
```

**Comment by nicklockwood** [comment]
@bbrk24 I'm not able to reproduce this now, so I assume it has been fixed

**Comment by bbrk24** [comment]
I'm still seeing this on 0.58.4. Here's the full output of the command, with some file paths redacted:

```
Running SwiftFormat...
Reading config file at [PATH REDACTED]/.swiftformat
error: [redundantSelf] Expected { on line 60 in [PATH REDACTED].swift.
```

(The code is still the same, it's just one line further down because something else was added earlier in the file.)

**Comment by nicklockwood** [comment]
Can you share the whole file (or whatever subset of it will reproduce the issue when formatted in isolation - it doesn't need to compile as long as it's syntactically valid)?

**Comment by bbrk24** [comment]
I'll try to strip it down to something that still demonstrates the issue. I can't upload the whole file verbatim as it's a private codebase.

**Comment by bbrk24** [comment]
Here's some (syntactically valid but semantically nonsense) code that reproduces the issue:

```swift
class Foo {
    func setUpView() async {
        let responses = await withTaskGroup(of: (Int, CalculatedResult)?.self) { group in
            for await case let (index, result)? in group {
                responses[index] = result
            }
        }
    }
}

```

Yep, that's the entire file.

**Comment by nicklockwood** [comment]
@bbrk24 I still can't reproduce this. Could I see your .swiftformat config?

**Comment by bbrk24** [comment]
Sure. If it helps, we're passing `--swiftversion 5.10`, because this project is being compiled with the Swift 5 language mode (and we have no intention to upgrade this specific project to Swift 6 for the foreseeable future), and I didn't see any flags for separate compiler and language versions.

I renamed the file to `swiftformat.txt` so that GitHub would accept the upload.

[swiftformat.txt](https://github.com/user-attachments/files/22977543/swiftformat.txt)

**Comment by nicklockwood** [comment]
> If it helps, we're passing --swiftversion 5.10, because this project is being compiled with the Swift 5 language mode (and we have no intention to upgrade this specific project to Swift 6 for the foreseeable future), and I didn't see any flags for separate compiler and language versions.

The `--swiftversion` flag is actually for the compiler version, so you should be fine to update it to `--swiftversion 6.2` and then set `--language-mode 5` to indicate you're using Swift 5 mode.

(I don't currently have any reason to think this is related to the problem you are seeing though)

**Comment by nicklockwood** [comment]
I was able to repro - thanks! Fix incoming

**Comment by nicklockwood** [comment]
@bbrk24 fixed in 0.58.5
