### ISSUE TITLE
Incorrect indenting of closures

### ISSUE THREAD

**Issue by tonyarnold** [nicklockwood/SwiftFormat#33]
Closures aren't being correctly indented, as shown in the examples below. This is happening whether there are parameters in the closure or not.

## Incorrect

```swift
for validatableResult in validatableResults {
    validatableResult
        .filter { (_, field) in field.isFocused }
        .observeIn(DispatchQueue.main.context)
        .observeNext { [unowned self] (result, field) in
        if result.isNotValid {
            self.expressionResultPopoverController.showResult(for: result, attachedTo: field)
        } else {
            self.expressionResultPopoverController.performClose()
        }
    }
        .disposeIn(disposeBag)
}
```

## Correct

```swift
for validatableResult in validatableResults {
    validatableResult
        .filter { (_, field) in field.isFocused }
        .observeIn(DispatchQueue.main.context)
        .observeNext { [unowned self] (result, field) in
            if result.isNotValid {
                self.expressionResultPopoverController.showResult(for: result, attachedTo: field)
            } else {
                self.expressionResultPopoverController.performClose()
            }
        }
        .disposeIn(disposeBag)
}
```

**Comment by nicklockwood** [comment]
Thanks, I'll take a look.

**Comment by nicklockwood** [comment]
Fixed in version 0.11.1

**Comment by tonyarnold** [comment]
Sorry Nick, I'm still getting slightly incorrect results on the code I posted above with 0.11.1.

I'm getting:

```swift
for validatableResult in validatableResults {
    validatableResult
        .filter { (_, field) in field.isFocused }
        .observeIn(DispatchQueue.main.context)
        .observeNext { [unowned self](result, field) in
        if result.isNotValid {
            self.expressionResultPopoverController.showResult(for: result, attachedTo: field)
        } else {
            self.expressionResultPopoverController.performClose()
        }
    }
    .disposeIn(disposeBag)
}
```

I would expect:

```swift
for validatableResult in validatableResults {
    validatableResult
        .filter { (_, field) in field.isFocused }
        .observeIn(DispatchQueue.main.context)
        .observeNext { [unowned self](result, field) in
             if result.isNotValid {
                 self.expressionResultPopoverController.showResult(for: result, attachedTo: field)
            } else {
                 self.expressionResultPopoverController.performClose()
            }
        }
        .disposeIn(disposeBag)
}
```

**Comment by nicklockwood** [comment]
Oh, hmm. I thought I'd run it on that example. OK, I'll check again. Thanks!

**Comment by nicklockwood** [comment]
OK, I see the problem - it behaves differently inside a for-loop. I'll take another crack at it :-)

**Comment by nicklockwood** [comment]
Should be working in 0.11.2

**Comment by tonyarnold** [comment]
👌 Perfect. Thankyou, sir!
