### ISSUE TITLE
Illegal instruction: 4 error in version 0.43.5

### ISSUE THREAD

**Issue by timbms** [nicklockwood/SwiftFormat#532]
I see a similar pattern to #331 when running the version installed via cocoapods

> ${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat --verbose . 
 
I get the following error 
....
```
Formatting /Users/tms/Developer/openhab/openhab-develop-20191117/openHABWatchSwift Extension/openHABWatch Extension/app/AppConstants.swift
Illegal instruction: 4
```

Seems to be related to all small files with <10 lines of code

**Comment by nicklockwood** [comment]
@timbms thanks for reporting this - could you share an example file that demonstrates the issue?

**Comment by timbms** [comment]
Here is an example file
[charStyle.zip](https://github.com/nicklockwood/SwiftFormat/files/4060592/charStyle.zip)

**Comment by nicklockwood** [comment]
I'm not able to reproduce this with 0.43.5 and the swift file you sent. Could there be some other factor involved?

**Comment by nicklockwood** [comment]
I tested using the homebrew install with the following command:

```bash
$ swiftformat ~/Downloads/openHAB/ChartStyle.swift --verbose
```

Does that also reproduce the error for you, or does it have to be a Cocoapods install?

**Comment by timbms** [comment]
Homebrew install is indeed without error. Problem occurs only with cocoapods install

**Comment by nicklockwood** [comment]
@timbms I believe this should be fixed in 0.44.0. Please verify.

**Comment by timbms** [comment]
0.44.0 still shows the same error with installation by cocoa pods
How could I trace this further?

**Comment by timbms** [comment]
I played with the .swiftformat file. 
The offending rule seems to be the last line with the attached .swiftformat file. If I comment out the header file, everything runs smoothly. 
Just changed filename to swiftformat.txt to make it uploadable on GitHub
[swiftformat.txt](https://github.com/nicklockwood/SwiftFormat/files/4082835/swiftformat.txt)

**Comment by nicklockwood** [comment]
@timbms thanks for digging into this. It should now be fixed in 0.44.1.
