### ISSUE TITLE
Braces Not Being Formatted for Structs, Extensions, or if-statements

### ISSUE THREAD

**Issue by PompeiaPaetenari** [nicklockwood/SwiftFormat#565]
Hello again,

When I have code like the following:
```swift
struct ConsoleError: Error {
	var errorCode: Int32
	init(_ errorCode: Int32)
	{
		self.errorCode = errorCode
	}
}
```
And attempt to run SwiftFormat, either through the Xcode extension or command line, it does not change the brace indentation to allman style (or back again) when either option is specified.  It does for the `init() {}` part, but not the `struct` itself.

As far as I can tell, it is only performing the correct swapping of brace-style for functions, protocols, and enums.

For reference::
```
$ swiftformat --version
0.44.2
```

**Comment by nicklockwood** [comment]
@PompeiaPaetenari thanks for reporting, I'll get it fixed asap.

**Comment by nicklockwood** [comment]
@PompeiaPaetenari fixed in 0.44.3.

**Comment by PompeiaPaetenari** [comment]
Hi Nick,

This is still not formatting if-statements correctly for `--allman` style.  This is what I get when running the `--allman` option on a file after it has gone through the non-allman option:

```swift
if parsedIP.secondOctet == 92 {
	if parsedIP.thirdOctet >= 0, parsedIP.thirdOctet <= 19 {
		result = .success(.set(.phx))
	}
	else if parsedIP.thirdOctet >= 64, parsedIP.thirdOctet <= 83 {
		result = .success(.set(.ins))
	}
	else
	{
		result = .failure(.invalid)
	}
}
```

I would expect that the braces for these if-statements are also moved to their own line.

**Comment by nicklockwood** [comment]
@PompeiaPaetenari looks like I missed a case. I'll add some more tests, thanks.

**Comment by nicklockwood** [comment]
@PompeiaPaetenari fixed in 0.44.4. Thanks for reporting!

**Comment by PompeiaPaetenari** [comment]
So sorry to bother you again about this, but switch statements with tuples are still not happy (in either direction to allman or back):

```swift
	switch (firstOctet, secondOctet, thirdOctet, fourthOctet) {
		case (0, 0, 0, 0):
			return .failure(.unableToParseIP)

		case (10, 92, _, _):
			switch thirdOctet
			{
```
Got ^ after running with allman true.

```swift
  switch (firstOctet, secondOctet, thirdOctet, fourthOctet)
  {
  case (0, 0, 0, 0):
    return .failure(.unableToParseIP)

  case (10, 92, _, _):
    switch thirdOctet {
```
And ^ when I move the brace manually and run without `--allman`:
