### ISSUE TITLE
@dynamicMemberLookup needs `self` to access members, clashes with redudantSelf.

### ISSUE THREAD

**Issue by RabugenTom** [nicklockwood/SwiftFormat#864]
Hello,

In a struct annotated with `@dynamicMemberLookup`, we (apparently) can only access a dynamic member if we prefix it with `self`. If `redudantSelf` is enabled, `self`'s are removed without considering this case, and the formatted code does not compile anymore.

```swift
@dynamicMemberLookup
struct Wrapper {

  struct Wrapped {
    var string: String = "A"
  }

  let wrapped = Wrapped()

  subscript<T>(dynamicMember keyPath: KeyPath< Wrapped, T>) -> T { 
    wrapped[keyPath: keyPath] 
  }

  func work() {
    if self.string == "A" {  // This compiles
      //…
    }
    if string == "A" {  // This is the formatted expression with redudantSelf enabled. Does not compile, on Xcode 12.5b1 at least
      //…
    }
  }

}
```

**Comment by nicklockwood** [comment]
@RabugenTom fixed in 0.47.12

**Comment by kylebshr** [comment]
This is still an issue for extensions of types with `@dynamicMemberLookup`. I created a new issue here: https://github.com/nicklockwood/SwiftFormat/issues/983
